name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-build:
    name: test-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            opendata/solr:${{ github.sha }}
            opendata/solr:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-release:
    name: test-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: semantic release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          branch: master
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
